import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useMe } from '../auth/useAuth';
import { coordinarCalidad, fetchCalidad, iniciarCalidad, resolverCalidad, type ChecklistCalidad, type RondaCalidad } from './calidadApi';
import { fechaHora } from './SeccionDisenoOperativa';
const campo = 'min-w-0 w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-tinta';
const boton = 'rounded-lg bg-tinta px-3 py-2 text-sm font-medium text-white disabled:opacity-50';
const fases: Record<number, string> = { 1: 'Validación de textos diagramados', 2: 'Validación de comentarios', 3: 'Revisión final', 4: 'Validación final de comentarios' };
const criterios: Record<string, string> = { textos_diagramados: 'Textos diagramados', palabras_cortadas: 'Palabras cortadas', citas: 'Citas', epigrafes: 'Epígrafes', paginas_ejercicios: 'Páginas de ejercicios', portadillas: 'Portadillas', sangria: 'Sangría', casita_panhouse: 'Casita PanHouse', logo_coleccion: 'Logo de colección', creditos: 'Créditos / números legales', notas_pie: 'Notas a pie', titulos: 'Títulos', intertitulos: 'Intertítulos', vinetas: 'Viñetas', indice: 'Índice y cuerpo de tripa', paginacion: 'Enumeración de páginas', foliaturas: 'Foliaturas', fotografias: 'Fotografías', tablas: 'Tablas', dedicatoria: 'Dedicatoria', agradecimientos: 'Agradecimientos', sobre_autor: 'Sobre el autor', prologo: 'Prólogo', comentarios: 'Comentarios', datos: 'Fechas, nombres y lugares', textos_incorporar: 'Archivos / textos por incorporar' };
export function TarjetaCalidad({ ronda: q }: { ronda: RondaCalidad }) {
  const { data: user } = useMe(); const qc = useQueryClient();
  const [due, setDue] = useState(''); const [archivo, setArchivo] = useState(''); const [observaciones, setObservaciones] = useState('');
  const [cantidad, setCantidad] = useState(0); const [paginas, setPaginas] = useState(''); const [pendientes, setPendientes] = useState(0); const [nuevos, setNuevos] = useState(0);
  const [lista, setLista] = useState<ChecklistCalidad>(q.checklist ?? {}); const [legales, setLegales] = useState('');
  const accion = useMutation({ mutationFn: (fn: () => Promise<unknown>) => fn(), onSuccess: () => { qc.invalidateQueries({ queryKey: ['calidad'] }); qc.invalidateQueries({ queryKey: ['diseno'] }); qc.invalidateQueries({ queryKey: ['ficha', q.proyectoId] }); } });
  const validacion = q.numeroFase === 2 || q.numeroFase === 4;
  const total = validacion ? pendientes + nuevos : cantidad;
  const resolver = (aprobar: boolean) => accion.mutate(() => resolverCalidad(q.id, { aprobar, cantidadComentarios: total, cantidadPaginas: paginas ? Number(paginas) : undefined,
    comentariosUrl: archivo || undefined, observaciones: observaciones || undefined, checklist: q.criterios.length ? lista : undefined,
    cambiosPendientesPorAplicar: validacion ? pendientes : undefined, cambiosNuevosSugeridos: validacion ? nuevos : undefined }));
  return <article className="min-w-0 rounded-xl border border-tinta/10 bg-white p-4 shadow-sm sm:p-5">
    <header className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-tinta">F{q.numeroFase}.{q.ronda} · {fases[q.numeroFase]}</h3><p className="break-words text-sm text-gray-500">{q.autorNombre} · #{q.proyectoCodigo} · {q.pdfVersion}</p></div><span className={`rounded-full px-3 py-1 text-xs ${q.aprobado ? 'bg-green-100 text-green-800' : q.aprobado === false ? 'bg-amber-100 text-amber-900' : 'bg-dorado/15 text-tinta'}`}>{!q.activa ? 'Histórica' : q.listoPaqueteFinal ? 'Lista para paquete final' : q.aprobado ? 'Aprobada' : q.aprobado === false ? 'Ajustes en Diseño' : 'Pendiente de revisión'}</span></header>
    <dl className="mt-4 grid grid-cols-1 gap-3 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">Vencimiento</dt><dd>{fechaHora(q.dueAt)}</dd></div><div><dt className="text-gray-500">Revisor real</dt><dd>{q.nombreQuienRecibe ?? 'Bandeja compartida'}</dd></div><div><dt className="text-gray-500">Resultado registrado</dt><dd>{fechaHora(q.revisadoEn)}</dd></div></dl>
    {q.diasReferencia && <p className="mt-2 text-xs text-gray-500">Referencia del Manual: {q.diasReferencia} día · calendario por confirmar.</p>}
    <nav className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-tinta underline" aria-label="Archivos de la ronda">{[[q.pdfUrl, 'PDF a validar'], [q.fuenteUrl, 'Tripa fuente'], [q.versionAnteriorUrl, 'Versión anterior'], [q.comentariosAnterioresUrl, 'Comentarios por verificar'], [q.numerosLegalesUrl, 'Números legales'], [q.comentariosUrl, 'PDF comentado de esta ronda']].filter(([url]) => url).map(([url, label]) => <a key={label} href={url!} target="_blank" rel="noreferrer">{label}</a>)}</nav>
    {q.observaciones && <p className="mt-3 whitespace-pre-wrap break-words text-sm text-gray-600">{q.observaciones}</p>}
    {q.activa && q.version.feedbackEn && <p className="mt-3 whitespace-pre-wrap break-words text-sm text-amber-800">Ajustes pendientes en Diseño: {q.version.feedback}{q.version.feedbackArchivoUrl && <a className="ml-2 underline" href={q.version.feedbackArchivoUrl} target="_blank" rel="noreferrer">PDF con comentarios</a>}</p>}
    {q.tripaLista && <p className="mt-3 text-sm text-green-700">Tripa aprobada en revisión final. {q.cubiertaLista ? 'Tripa y cubierta listas para solicitar paquete final.' : 'Siguiente paso: completar aprobación de cubierta.'}</p>}
    {q.revisadoEn && <p className="mt-2 text-sm text-gray-500">Comentarios: {q.cantidadComentarios ?? 0}{validacion ? ` · Por verificar: ${q.cambiosPorVerificar ?? 0} · Pendientes: ${q.cambiosPendientesPorAplicar ?? 0} · Nuevos: ${q.cambiosNuevosSugeridos ?? 0}` : ''}</p>}
    {q.activa && !q.revisadoEn && user?.rol === 'soporte_editorial' && <div className="mt-4 space-y-3 border-t border-gray-100 pt-4">
      {!q.iniciadoEn && <div className="flex flex-col gap-2 sm:flex-row"><label className="flex-1 text-xs text-gray-600">Pautar vencimiento exacto<input type="datetime-local" className={campo} value={due} onChange={e => setDue(e.target.value)} /></label><button className={boton} disabled={accion.isPending} onClick={() => accion.mutate(() => iniciarCalidad(q.id, due ? new Date(due).toISOString() : undefined))}>Iniciar revisión</button></div>}
      {q.criterios.length > 0 && <details className="rounded-lg border border-gray-200 p-3" open><summary className="cursor-pointer text-sm font-medium text-tinta">Lista de revisión</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{q.criterios.map(c => <div key={c} className="min-w-0"><label className="block text-xs text-gray-600">{criterios[c] ?? c}<select className={campo} value={!Object.hasOwn(lista, c) ? '' : lista[c].cumple === null ? 'na' : lista[c].cumple ? 'si' : 'no'} onChange={e => setLista(prev => { const next = { ...prev }; if (!e.target.value) delete next[c]; else next[c] = { ...prev[c], cumple: e.target.value === 'na' ? null : e.target.value === 'si' }; return next; })}><option value="">Sin revisar</option><option value="si">Cumple</option><option value="no">Requiere corrección</option><option value="na">No aplica</option></select></label><input className={`${campo} mt-1`} aria-label={`Observaciones: ${criterios[c] ?? c}`} placeholder="Observaciones del criterio" value={lista[c]?.observaciones ?? ''} disabled={!Object.hasOwn(lista, c)} onChange={e => setLista(prev => ({ ...prev, [c]: { ...prev[c], observaciones: e.target.value } }))} /></div>)}</div></details>}
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-gray-600">PDF con comentarios<input type="url" className={campo} value={archivo} onChange={e => setArchivo(e.target.value)} /></label><label className="text-xs text-gray-600">Páginas revisadas<input type="number" min="1" className={campo} value={paginas} onChange={e => setPaginas(e.target.value)} /></label></div>
      {validacion ? <div className="grid gap-3 sm:grid-cols-3"><p className="text-sm text-gray-600">Por verificar: {q.cambiosPorVerificar ?? 0}</p><label className="text-xs text-gray-600">Pendientes por aplicar<input type="number" min="0" className={campo} value={pendientes} onChange={e => setPendientes(Number(e.target.value))} /></label><label className="text-xs text-gray-600">Cambios nuevos sugeridos<input type="number" min="0" className={campo} value={nuevos} onChange={e => setNuevos(Number(e.target.value))} /></label></div> : <label className="block text-xs text-gray-600">Total de comentarios por aplicar<input type="number" min="0" className={campo} value={cantidad} onChange={e => setCantidad(Number(e.target.value))} /></label>}
      <label className="block text-xs text-gray-600">Observaciones de la revisión<textarea className={campo} value={observaciones} onChange={e => setObservaciones(e.target.value)} /></label><div className="flex flex-wrap gap-2"><button className={boton} disabled={accion.isPending} onClick={() => resolver(true)}>Aprobar versión</button><button className={boton} disabled={!archivo || accion.isPending} onClick={() => resolver(false)}>Devolver comentarios a Diseño</button></div>
    </div>}
    {q.activa && q.aprobado && q.numeroFase <= 2 && !q.version.feedbackEn && user?.rol === 'especialista' && <div className="mt-4 space-y-3 border-t border-gray-100 pt-4">
      {!q.version.enviadaAutorEn ? <><label className="block text-xs text-gray-600">Pautar feedback del autor (referencia: un día)<input type="datetime-local" className={campo} value={due} onChange={e => setDue(e.target.value)} /></label><button className={boton} disabled={accion.isPending} onClick={() => accion.mutate(() => coordinarCalidad(q.id, { accion: 'enviar_autor', feedbackAutorDueAt: due ? new Date(due).toISOString() : undefined }))}>Registrar envío al autor</button></> : !q.version.aprobadaAutorEn ? <><label className="block text-xs text-gray-600">Feedback del autor<textarea className={campo} value={observaciones} onChange={e => setObservaciones(e.target.value)} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-gray-600">PDF con comentarios del autor<input type="url" className={campo} value={archivo} onChange={e => setArchivo(e.target.value)} /></label><label className="text-xs text-gray-600">Cantidad de comentarios<input type="number" min="1" className={campo} value={cantidad} onChange={e => setCantidad(Number(e.target.value))} /></label></div><div className="flex flex-wrap gap-2"><button className={boton} disabled={accion.isPending} onClick={() => accion.mutate(() => coordinarCalidad(q.id, { accion: 'aprobar_autor' }))}>Registrar aprobación del autor</button><button className={boton} disabled={!archivo || !observaciones.trim() || accion.isPending} onClick={() => accion.mutate(() => coordinarCalidad(q.id, { accion: 'feedback_autor', feedback: observaciones, comentariosUrl: archivo, cantidadComentarios: cantidad }))}>Enviar feedback a Diseño</button></div></> : <><label className="block text-xs text-gray-600">Enlace a números legales de RRPP (si están disponibles)<input type="url" className={campo} value={legales} onChange={e => setLegales(e.target.value)} /></label><p className="text-xs text-gray-500">Calidad verifica los números adjuntos o indica su incorporación en el PDF comentado.</p><button className={boton} disabled={accion.isPending} onClick={() => accion.mutate(() => coordinarCalidad(q.id, { accion: 'revision_final', numerosLegalesUrl: legales || undefined }))}>Solicitar revisión final</button></>}
      {q.version.enviadaAutorEn && <p className="text-xs text-gray-500">Enviado: {fechaHora(q.version.enviadaAutorEn)} · Feedback pautado: {fechaHora(q.version.feedbackAutorDueAt)}</p>}
    </div>}
    {q.checklist && q.revisadoEn && <details className="mt-3 text-sm"><summary className="cursor-pointer text-gray-500">Criterios revisados</summary><ul className="mt-2 space-y-1">{Object.entries(q.checklist).map(([c, val]) => <li key={c} className="break-words">{criterios[c] ?? c}: {val.cumple === null ? 'No aplica' : val.cumple ? 'Cumple' : 'Corrección requerida'}{val.observaciones ? ` · ${val.observaciones}` : ''}</li>)}</ul></details>}
    {accion.error && <p role="alert" className="mt-3 text-sm text-red-700">{accion.error instanceof Error ? accion.error.message : 'No se pudo completar'}</p>}
  </article>;
}
export function SeccionCalidadOperativa({ proyectoId }: { proyectoId?: string }) {
  const { data: user } = useMe();
  const permitido = !!user && ['especialista', 'disenador', 'soporte_editorial', 'jefe_area'].includes(user.rol);
  const q = useQuery({ queryKey: ['calidad', proyectoId ?? 'bandeja'], queryFn: () => fetchCalidad(proyectoId), enabled: permitido });
  if (!permitido) return null;
  const activas = (q.data?.rondas ?? []).filter(r => r.activa).sort((a, b) => Number(!!a.revisadoEn) - Number(!!b.revisadoEn) || (a.dueAt ?? 'z').localeCompare(b.dueAt ?? 'z'));
  const historia = (q.data?.rondas ?? []).filter(r => !r.activa);
  return <section className="min-w-0 space-y-4"><h2 className="text-xl font-bold text-tinta">{proyectoId ? 'Calidad y validación' : 'Bandeja de Calidad'}</h2>{q.isLoading && <p>Cargando rondas…</p>}{q.error && <p role="alert" className="text-sm text-red-700">{q.error instanceof Error ? q.error.message : 'No se pudo cargar'}</p>}{q.data && !activas.length && <p className="text-sm text-gray-500">Sin rondas activas.</p>}{activas.map(r => <TarjetaCalidad key={r.id} ronda={r} />)}{historia.length > 0 && <details className="rounded-lg border border-gray-200 p-3"><summary className="cursor-pointer text-sm text-gray-500">Historial de validaciones ({historia.length})</summary><div className="mt-3 space-y-3">{historia.map(r => <TarjetaCalidad key={r.id} ronda={r} />)}</div></details>}</section>;
}
